import type { Config } from "@react-router/dev/config";

export default {
  ssr: false,
  appDirectory: "src",
  buildDirectory: "dist",
  basename: process.env.VITE_BASE_PATH ?? "/",
  future: {
    v8_middleware: true,
    v8_splitRouteModules: true,
    v8_viteEnvironmentApi: true,
    v8_passThroughRequests: true,
  },
  prerender: [
    "/",
    "/adventures",
    "/404",
    "/contribute",
    "/sponsors",
    "/about",
    "/handbook",
    "/privacy",
    "/accessibility",
    "/brand",
    // GENERATED:adventures
    "/adventures/lex-imperfecta",
    "/adventures/lex-imperfecta/levels/beginner",
    "/adventures/lex-imperfecta/levels/intermediate",
    "/adventures/lex-imperfecta/levels/expert",
    "/adventures/blind-by-design",
    "/adventures/blind-by-design/levels/beginner",
    "/adventures/blind-by-design/levels/intermediate",
    "/adventures/blind-by-design/levels/expert",
    "/adventures/the-ai-observatory",
    "/adventures/the-ai-observatory/levels/beginner",
    "/adventures/the-ai-observatory/levels/intermediate",
    "/adventures/the-ai-observatory/levels/expert",
    "/adventures/building-cloudhaven",
    "/adventures/building-cloudhaven/levels/beginner",
    "/adventures/building-cloudhaven/levels/intermediate",
    "/adventures/building-cloudhaven/levels/expert",
    "/adventures/echoes-lost-in-orbit",
    "/adventures/echoes-lost-in-orbit/levels/beginner",
    "/adventures/echoes-lost-in-orbit/levels/intermediate",
    "/adventures/echoes-lost-in-orbit/levels/expert",
    // /GENERATED:adventures
    // GENERATED:solutions
    "/adventures/echoes-lost-in-orbit/levels/beginner/solution",
    "/adventures/echoes-lost-in-orbit/levels/expert/solution",
    "/adventures/echoes-lost-in-orbit/levels/intermediate/solution",
    // /GENERATED:solutions
    "/challenges",
    // GENERATED:challenge-tags
    "/challenges/argo-cd",
    "/challenges/argo-rollouts",
    "/challenges/flagd",
    "/challenges/github-actions",
    "/challenges/grafana",
    "/challenges/jaeger",
    "/challenges/java",
    "/challenges/kubernetes",
    "/challenges/kyverno",
    "/challenges/openfeature",
    "/challenges/openllmetry",
    "/challenges/opentelemetry",
    "/challenges/opentofu",
    "/challenges/policy-reporter",
    "/challenges/prometheus",
    "/challenges/promql",
    "/challenges/python",
    "/challenges/spring-boot",
    "/challenges/tdd",
    "/challenges/terraform",
    "/challenges/trivy",
    // /GENERATED:challenge-tags
  ],
} satisfies Config;
