// This file is auto-generated by scripts/generate-solutions.mjs. Do not edit by hand.
import type { Solution } from "./types";

import { solution as solution_echoes_lost_in_orbit_beginner } from "./echoes-lost-in-orbit/beginner";

export const SOLUTIONS: Solution[] = [
  solution_echoes_lost_in_orbit_beginner,
];
