// This file is auto-generated by scripts/generate-solutions.mjs. Do not edit by hand.

export const SOLUTION_IDS: Set<string> = new Set([
  "echoes-lost-in-orbit/beginner",
  "echoes-lost-in-orbit/expert",
  "echoes-lost-in-orbit/intermediate",
]);
