// Generated by scripts/generate-adventures.mjs — do not edit by hand.
import type { AdventureCardSummary, AdventureContributor, RelatedLevelSummary } from "./types";

export const ADVENTURE_SUMMARIES: AdventureCardSummary[] = [
  {
    id: "dead-reckoning",
    title: "Dead Reckoning",
    month: "JUL 2026",
    story: "The Grand Fleet's commission office is buried in complaints. Manifests are filed but nothing comes of them. Vessels that do sail arrive at port with the wrong cargo, and no one along the route can explain why. As the fleet's engineer, your mission is to restore order from keel to quayside and find out what the records are hiding.",
    tags: ["Backstage", "Gitea", "Argo Events", "Argo Workflows", "Argo CD"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "<abbr data-title=\"Developer Relations\" tabindex=\"0\" aria-describedby=\"abbr-exp-62\">DevRel</abbr><span id=\"abbr-exp-62\" class=\"sr-only\">Developer Relations</span> at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    isLive: true,
    icon: "Compass",
    levels: [
      {
        id: "beginner",
        name: "Laying the Keel",
        difficulty: "Beginner",
        topics: ["Backstage", "Gitea"],
        learnings: [
          "How Backstage <a href=\"https://backstage.io/docs/features/software-templates/writing-templates\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">software templates</a> are structured: parameters, steps, and output",
          "How scaffolder <a href=\"https://backstage.io/docs/features/software-templates/builtin-actions\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">actions</a> work, such as <code>fetch:template</code>, <code>publish:gitea</code>, and <code>catalog:register</code>",
          "How the <a href=\"https://backstage.io/docs/features/software-catalog/life-of-an-entity\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">catalog registration</a> step connects a scaffolded repository to the Backstage catalog",
          "How to use Backstage's built-in <a href=\"https://backstage.io/docs/features/software-templates/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">template tooling</a>: the installed-actions browser and the Template Editor's live preview and dry-run",
        ],
      },
      {
        id: "intermediate",
        name: "Sea Trial",
        difficulty: "Intermediate",
        topics: ["Backstage", "Gitea", "Argo Events", "Argo Workflows", "Argo CD"],
        learnings: [
          "How a Git webhook drives a workflow engine: Argo Events <a href=\"https://argoproj.github.io/argo-events/concepts/sensor/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Sensors</a> turn a push into a <a href=\"https://argoproj.github.io/argo-events/tutorials/02-parameterization/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">parameterized</a> workflow run",
          "How <a href=\"https://argo-workflows.readthedocs.io/en/latest/walk-through/steps/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Argo Workflows</a> runs a multi-step delivery pipeline, and the <a href=\"https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">RBAC</a> its steps need",
          "How an Argo CD <a href=\"https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">ApplicationSet</a> auto-discovers repos and <a href=\"https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">syncs</a> them into the cluster",
          "How Backstage <a href=\"https://backstage.io/docs/features/software-catalog/well-known-annotations\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">annotations</a> tie a catalog entity to its live deployment status",
          "How to trace a silent failure across tools from each one's logs and UI",
        ],
      },
      {
        id: "expert",
        name: "The Chronometer",
        difficulty: "Expert",
        topics: ["Backstage", "Argo Workflows", "Argo CD", "OpenTelemetry", "Jaeger"],
        learnings: [
          "How trace context crosses an asynchronous boundary with no call chain: a commission carries its <a href=\"https://www.w3.org/TR/trace-context/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">W3C traceparent</a> to a push-triggered pipeline, so its spans <a href=\"https://opentelemetry.io/docs/concepts/context-propagation/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">continue the same trace</a> instead of starting a new one",
          "Why a <a href=\"https://opentelemetry.io/docs/concepts/signals/traces/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">distributed trace</a> reveals what per-tool logs cannot: the value that flowed through each step, so a fault surfaces where the data diverges",
          "How to read that trace in <a href=\"https://www.jaegertracing.io/docs/latest/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Jaeger</a> to localise a fault to a single service by following one attribute across the whole voyage",
        ],
      },
    ],
  },
  {
    id: "lex-imperfecta",
    title: "Lex Imperfecta",
    month: "JUN 2026",
    story: "The Roman Republic has built a sophisticated legal system to protect its citizens — but the laws were written in haste, and the exceptions were written too generously. Policies go unenforced, the wrong citizens are exempt, and something has slipped through the gates unnoticed. As a newly appointed Praetor, your mission is to restore order before chaos takes hold.",
    tags: ["Kyverno", "Policy Reporter", "Kubernetes"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "<abbr data-title=\"Developer Relations\" tabindex=\"0\" aria-describedby=\"abbr-exp-62\">DevRel</abbr><span id=\"abbr-exp-62\" class=\"sr-only\">Developer Relations</span> at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    icon: "Scale",
    levels: [
      {
        id: "beginner",
        name: "The Twelve Tables",
        difficulty: "Beginner",
        topics: ["Kyverno", "Kubernetes"],
        learnings: [
          "How Kyverno <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">ValidatingPolicy</a> resources and  <a href=\"https://kubernetes.io/docs/reference/using-api/cel/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\"><abbr data-title=\"Common Expression Language\" tabindex=\"0\" aria-describedby=\"abbr-exp-63\">CEL</abbr><span id=\"abbr-exp-63\" class=\"sr-only\">Common Expression Language</span> validation expressions</a> work",
          "The difference between <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Audit, Deny, and Warn</a> validation actions",
          "How to use <a href=\"https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">custom label keys</a> to  enforce workload identity standards",
          "How Kyverno <a href=\"https://kyverno.io/docs/policy-types/mutating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">MutatingPolicy</a> resources automatically  patch incoming workloads at admission",
        ],
      },
      {
        id: "intermediate",
        name: "Governing the Provinces",
        difficulty: "Intermediate",
        topics: ["Kyverno", "Policy Reporter", "Kubernetes"],
        learnings: [
          "How to scope policies using <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">ValidatingPolicy</a> (cluster-wide) and <a href=\"https://kyverno.io/docs/policy-types/validating-policy/#policy-scope\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">NamespacedValidatingPolicy</a> (per-namespace), and when to use each",
          "How <a href=\"https://kubernetes.io/docs/reference/using-api/cel/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">CEL expressions</a> in <code>ValidatingPolicy</code> and <code>PolicyException</code> express fine-grained admission conditions",
          "How to write and scope a <a href=\"https://kyverno.io/docs/guides/exceptions/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">PolicyException</a> correctly so only the intended workloads are exempt",
          "How to use <a href=\"https://kyverno.github.io/policy-reporter/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Policy Reporter</a> and the <a href=\"https://openreports.io/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">OpenReports</a> format to audit and debug a policy estate across multiple namespaces",
        ],
      },
      {
        id: "expert",
        name: "Quis Custodiet",
        difficulty: "Expert",
        topics: ["Kyverno", "Policy Reporter", "Kubernetes"],
        learnings: [
          "How <a href=\"https://falco.org/docs/reference/rules/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Falco rules</a> are structured: conditions, output, and kernel-level fields, and how to write a rule targeting a specific runtime behaviour",
          "Why <code>privileged: false</code> is not enough: how <a href=\"https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Linux capabilities</a> grant host-level access without the privileged flag",
          "How to use <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">spec.variables</a> in a <code>ValidatingPolicy</code> to share reusable CEL expressions across validations",
          "How pod volumes reference secrets, and why a volume's name and the secret it mounts are two separate fields in the pod spec",
          "How <a href=\"https://github.com/falcosecurity/falcosidekick\" target=\"_blank\" rel=\"noopener noreferrer\" aria-describedby=\"new-tab-hint\">Falcosidekick</a> aggregates Falco alerts and how to use its UI to watch a runtime incident in real time",
        ],
      },
    ],
  },
  {
    id: "blind-by-design",
    title: "Blind by Design",
    month: "MAY 2026",
    story: "Three levels of OpenFeature with flagd as the provider, in a Java + Spring Boot service. Wire the SDK against a flagd sidecar (Beginner), layer evaluation context to target by cohort (Intermediate), then instrument flag evaluations with OpenTelemetry and roll back a misbehaving fractional rollout (Expert). All without redeploying.",
    tags: ["OpenFeature", "flagd", "Spring Boot", "Java", "OpenTelemetry", "Grafana"],
    contributor: {
      name: "Simon Schrottner",
      url: "https://schrottner.at/",
      aboutHtml: "<abbr data-title=\"Cloud Native Computing Foundation\" tabindex=\"0\" aria-describedby=\"abbr-exp-64\">CNCF</abbr><span id=\"abbr-exp-64\" class=\"sr-only\">Cloud Native Computing Foundation</span> Ambassador and maintainer of OpenFeature and JUnit Pioneer. Helps teams release faster and with more confidence through open standards, feature flagging, and the communities that make both possible. A familiar face at KubeCon EU, Devoxx, ContainerDays, and meetups across Europe.",
    },
    icon: "FlaskConical",
    levels: [
      {
        id: "beginner",
        name: "Stand up the Lab",
        difficulty: "Beginner",
        topics: ["OpenFeature", "flagd", "Spring Boot"],
        learnings: [
          "How an OpenFeature client and provider work together: the <abbr data-title=\"Software Development Kit\" tabindex=\"0\" aria-describedby=\"abbr-exp-65\">SDK</abbr><span id=\"abbr-exp-65\" class=\"sr-only\">Software Development Kit</span> is provider-agnostic and the flagd provider plugs in via dependency only",
          "What remote provider means in practice: the SDK calls a separate flag service (flagd) over <abbr data-title=\"Google Remote Procedure Call\" tabindex=\"0\" aria-describedby=\"abbr-exp-66\">gRPC</abbr><span id=\"abbr-exp-66\" class=\"sr-only\">Google Remote Procedure Call</span>, not parsing flags.json itself",
          "What flags.json looks like for flagd (state, variants, defaultVariant)",
          "Why hot-reload of the flag file matters operationally: configuration without redeploy",
        ],
      },
      {
        id: "intermediate",
        name: "Outcome by Cohort",
        difficulty: "Intermediate",
        topics: ["OpenFeature", "flagd", "Spring Boot", "Java"],
        learnings: [
          "How OpenFeature's transaction-context propagation works in a thread-per-request server, and why a ThreadLocalTransactionContextPropagator is the right primitive for Servlet-based apps",
          "The difference between request-scoped context (the subject's species) and global evaluation context (the trial's country), and when each is the right tool",
          "How hooks let you attach cross-cutting behaviour, audit logging today and OpenTelemetry tracing tomorrow, without modifying every flag evaluation call site",
        ],
      },
      {
        id: "expert",
        name: "Read the Chart",
        difficulty: "Expert",
        topics: ["OpenFeature", "OpenTelemetry", "Grafana", "Spring Boot"],
        learnings: [
          "How the OpenFeature OpenTelemetry hooks (TracesHook and MetricsHook) join flag evaluations to the rest of an application's telemetry without a separate ingestion path",
          "How to author your own Hook: a tiny class that copies merged-eval-context attributes onto the active <abbr data-title=\"OpenTelemetry\" tabindex=\"0\" aria-describedby=\"abbr-exp-67\">OTel</abbr><span id=\"abbr-exp-67\" class=\"sr-only\">OpenTelemetry</span> span, closing the loop between why a flag resolved the way it did and what the operator sees in Tempo",
          "How fractional rollout in flagd buckets users by targetingKey (same key, same bucket, every request) and how to read that bucketing off a dashboard",
          "How a flag flip is a faster operational lever than a redeploy when a rollout is misbehaving: the difference between a one-line config change and a twenty-minute deployment",
        ],
      },
    ],
  },
  {
    id: "the-ai-observatory",
    title: "The AI Observatory",
    month: "FEB 2026",
    story: "Investigate a mysterious bandwidth anomaly at a remote research station by instrumenting its AI system with OpenTelemetry, OpenLLMetry, and Jaeger.",
    tags: ["OpenTelemetry", "OpenLLMetry", "Jaeger", "Prometheus", "Python"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "<abbr data-title=\"Developer Relations\" tabindex=\"0\" aria-describedby=\"abbr-exp-62\">DevRel</abbr><span id=\"abbr-exp-62\" class=\"sr-only\">Developer Relations</span> at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    icon: "Telescope",
    levels: [
      {
        id: "beginner",
        name: "Calibrating the Lens",
        difficulty: "Beginner",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger"],
        learnings: [
          "Instrument Python AI apps with OpenLLMetry",
          "Analyze traces in Jaeger",
        ],
      },
      {
        id: "intermediate",
        name: "The Distracted Pilot",
        difficulty: "Intermediate",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger", "Prometheus"],
        learnings: [
          "Instrument <abbr data-title=\"Retrieval-Augmented Generation\" tabindex=\"0\" aria-describedby=\"abbr-exp-68\">RAG</abbr><span id=\"abbr-exp-68\" class=\"sr-only\">Retrieval-Augmented Generation</span> pipelines with OpenLLMetry",
          "Create custom OpenTelemetry metrics in Python",
          "Write PromQL queries &#x26; recording rules in Prometheus",
        ],
      },
      {
        id: "expert",
        name: "The Noise Filter",
        difficulty: "Expert",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger"],
        learnings: [
          "OpenTelemetry GenAI semantic conventions",
          "Tail sampling in the <abbr data-title=\"OpenTelemetry\" tabindex=\"0\" aria-describedby=\"abbr-exp-69\">OTel</abbr><span id=\"abbr-exp-69\" class=\"sr-only\">OpenTelemetry</span> Collector",
        ],
      },
    ],
  },
  {
    id: "building-cloudhaven",
    title: "Building CloudHaven",
    month: "JAN 2026",
    story: "Join the Infrastructure Guild and modernize CloudHaven's infrastructure from manual provisioning to a self-service platform using Infrastructure as Code. A hands-on journey through infrastructure as code with OpenTofu and GitHub Actions.",
    tags: ["OpenTofu", "Terraform", "GitHub Actions", "Trivy", "TDD"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "<abbr data-title=\"Developer Relations\" tabindex=\"0\" aria-describedby=\"abbr-exp-62\">DevRel</abbr><span id=\"abbr-exp-62\" class=\"sr-only\">Developer Relations</span> at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    icon: "Building2",
    levels: [
      {
        id: "beginner",
        name: "The Foundation Stones",
        difficulty: "Beginner",
        topics: ["OpenTofu"],
        learnings: [
          "Infrastructure as Code with OpenTofu",
          "Remote state management with <abbr data-title=\"Google Cloud Storage\" tabindex=\"0\" aria-describedby=\"abbr-exp-70\">GCS</abbr><span id=\"abbr-exp-70\" class=\"sr-only\">Google Cloud Storage</span> backend",
          "Dynamic resource provisioning with for_each",
          "Conditional resources with the enabled meta-argument, new in OpenTofu",
        ],
      },
      {
        id: "intermediate",
        name: "The Modular Metropolis",
        difficulty: "Intermediate",
        topics: ["OpenTofu", "TDD"],
        learnings: [
          "OpenTofu module testing with tofu test",
          "Test-Driven Development (TDD) workflow",
          "Input validation with custom rules",
          "Refactoring infrastructure safely with moved blocks",
        ],
      },
      {
        id: "expert",
        name: "The Guardian Protocols",
        difficulty: "Expert",
        topics: ["OpenTofu", "GitHub Actions", "Trivy"],
        learnings: [
          "GitHub Actions for drift detection and plan/apply",
          "Integration tests with service containers",
          "Security scanning with Trivy",
        ],
      },
    ],
  },
  {
    id: "echoes-lost-in-orbit",
    title: "Echoes Lost in Orbit",
    month: "DEC 2025",
    story: "Restore interstellar communications by fixing broken GitOps setups, progressive delivery systems, and observability pipelines across three galactic missions.",
    tags: ["Argo CD", "Argo Rollouts", "OpenTelemetry", "Jaeger", "PromQL"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "<abbr data-title=\"Developer Relations\" tabindex=\"0\" aria-describedby=\"abbr-exp-62\">DevRel</abbr><span id=\"abbr-exp-62\" class=\"sr-only\">Developer Relations</span> at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    icon: "Satellite",
    levels: [
      {
        id: "beginner",
        name: "Broken Echoes",
        difficulty: "Beginner",
        topics: ["Argo CD"],
        learnings: [
          "Debug <abbr data-title=\"Git Operations\" tabindex=\"0\" aria-describedby=\"abbr-exp-71\">GitOps</abbr><span id=\"abbr-exp-71\" class=\"sr-only\">Git Operations</span> flows with Argo CD",
          "ApplicationSet templating &#x26; pitfalls",
          "Environment isolation &#x26; namespaces",
          "Sync policies: automated, prune &#x26; self-heal",
        ],
      },
      {
        id: "intermediate",
        name: "The Silent Canary",
        difficulty: "Intermediate",
        topics: ["Argo Rollouts", "PromQL"],
        learnings: [
          "Progressive delivery with Argo Rollouts",
          "Canary deployments &#x26; automated analysis",
          "Write PromQL queries for health validation",
          "Kube-state-metrics for deployment decisions",
        ],
      },
      {
        id: "expert",
        name: "Hyperspace Operations & Transport",
        difficulty: "Expert",
        topics: ["Argo Rollouts", "OpenTelemetry", "Jaeger", "PromQL"],
        learnings: [
          "Configure OpenTelemetry Collector pipelines",
          "Spanmetrics connector (traces to metrics)",
          "Detect idle canaries with traffic validation",
          "Distributed tracing with Jaeger",
        ],
      },
    ],
  },
];

/** All unique technology tags across all adventures, for card and filter views. */
export const SUMMARY_TAGS: string[] = Array.from(
  new Set(ADVENTURE_SUMMARIES.flatMap((a) => a.tags))
).sort();

/** Returns level summaries matching a tag, for filtered card views on the home page. */
export const getLevelSummariesByTag = (tag: string): RelatedLevelSummary[] =>
  ADVENTURE_SUMMARIES
    .filter((a) => a.tags.includes(tag))
    .flatMap((a) =>
      a.levels.map((level) => ({
        level,
        adventureId: a.id,
        adventureTitle: a.title,
        ...(a.isLive ? { isLive: true } : {}),
        ...(a.icon ? { adventureIcon: a.icon } : {}),
      }))
    );

/**
 * Community members who contributed an adventure, grouped by person.
 * Derived from ADVENTURE_SUMMARIES — import from here instead of "@/data/adventures"
 * on pages that do not otherwise need the full adventure dataset (About, Adventures, Challenges).
 */
export const ADVENTURE_CONTRIBUTORS: AdventureContributor[] = Object.values(
  ADVENTURE_SUMMARIES
    .filter((a): a is AdventureCardSummary & { contributor: NonNullable<AdventureCardSummary["contributor"]> } => a.contributor !== undefined)
    .reduce<Record<string, AdventureContributor>>((acc, a) => {
      const key = a.contributor.name;
      if (!acc[key]) {
        acc[key] = { name: a.contributor.name, url: a.contributor.url, aboutHtml: a.contributor.aboutHtml, adventures: [] };
      }
      acc[key].adventures.push({ id: a.id, title: a.title });
      return acc;
    }, {})
);
