// Generated by scripts/generate-adventures.mjs — do not edit by hand.
import type { AdventureCardSummary, AdventureContributor, RelatedLevelSummary } from "./types";

export const ADVENTURE_SUMMARIES: AdventureCardSummary[] = [
  {
    id: "lex-imperfecta",
    title: "Lex Imperfecta",
    month: "JUN 2026",
    story: "The Roman Republic has built a sophisticated legal system to protect its citizens — but the laws were written in haste, and the exceptions were written too generously. Policies go unenforced, the wrong citizens are exempt, and something has slipped through the gates unnoticed. As a newly appointed Praetor, your mission is to restore order before chaos takes hold.",
    tags: ["Kyverno", "Kubernetes"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "DevRel at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    isLive: true,
    levels: [
      {
        id: "beginner",
        name: "The Twelve Tables",
        difficulty: "Beginner",
        topics: ["Kyverno", "Kubernetes"],
        learnings: [
          "How Kyverno <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\">ValidatingPolicy<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\" style=\"flex-shrink:0\"><path d=\"M15 3h6v6\"/><path d=\"M10 14 21 3\"/><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"/></svg><span class=\"sr-only\"> (opens in new tab)</span></a> resources and  <a href=\"https://kubernetes.io/docs/reference/using-api/cel/\" target=\"_blank\" rel=\"noopener noreferrer\">CEL validation expressions<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\" style=\"flex-shrink:0\"><path d=\"M15 3h6v6\"/><path d=\"M10 14 21 3\"/><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"/></svg><span class=\"sr-only\"> (opens in new tab)</span></a> work",
          "The difference between <a href=\"https://kyverno.io/docs/policy-types/validating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\">Audit, Deny, and Warn<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\" style=\"flex-shrink:0\"><path d=\"M15 3h6v6\"/><path d=\"M10 14 21 3\"/><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"/></svg><span class=\"sr-only\"> (opens in new tab)</span></a> validation actions",
          "How to use <a href=\"https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/\" target=\"_blank\" rel=\"noopener noreferrer\">custom label keys<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\" style=\"flex-shrink:0\"><path d=\"M15 3h6v6\"/><path d=\"M10 14 21 3\"/><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"/></svg><span class=\"sr-only\"> (opens in new tab)</span></a> to  enforce workload identity standards",
          "How Kyverno <a href=\"https://kyverno.io/docs/policy-types/mutating-policy/\" target=\"_blank\" rel=\"noopener noreferrer\">MutatingPolicy<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" focusable=\"false\" style=\"flex-shrink:0\"><path d=\"M15 3h6v6\"/><path d=\"M10 14 21 3\"/><path d=\"M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6\"/></svg><span class=\"sr-only\"> (opens in new tab)</span></a> resources automatically  patch incoming workloads at admission",
        ],
      },
    ],
  },
  {
    id: "blind-by-design",
    title: "Blind by Design",
    month: "MAY 2026",
    story: "Three levels of OpenFeature with flagd as the provider, in a Java + Spring Boot service. Wire the SDK against a flagd sidecar (Beginner), layer evaluation context to target by cohort (Intermediate), then instrument flag evaluations with OpenTelemetry and roll back a misbehaving fractional rollout (Expert). All without redeploying.",
    tags: ["OpenFeature", "flagd", "Spring Boot", "Java", "OpenTelemetry", "Grafana"],
    contributor: {
      name: "Simon Schrottner",
      url: "https://schrottner.at/",
      aboutHtml: "CNCF Ambassador and maintainer of OpenFeature and JUnit Pioneer. Helps teams release faster and with more confidence through open standards, feature flagging, and the communities that make both possible. A familiar face at KubeCon EU, Devoxx, ContainerDays, and meetups across Europe.",
    },
    levels: [
      {
        id: "beginner",
        name: "Stand up the Lab",
        difficulty: "Beginner",
        topics: ["OpenFeature", "flagd", "Spring Boot"],
        learnings: [
          "How an OpenFeature client and provider work together: the SDK is provider-agnostic and the flagd provider plugs in via dependency only",
          "What remote provider means in practice: the SDK calls a separate flag service (flagd) over gRPC, not parsing flags.json itself",
          "What flags.json looks like for flagd (state, variants, defaultVariant)",
          "Why hot-reload of the flag file matters operationally: configuration without redeploy",
        ],
      },
      {
        id: "intermediate",
        name: "Outcome by Cohort",
        difficulty: "Intermediate",
        topics: ["OpenFeature", "flagd", "Spring Boot", "Java"],
        learnings: [
          "How OpenFeature's transaction-context propagation works in a thread-per-request server, and why a ThreadLocalTransactionContextPropagator is the right primitive for Servlet-based apps",
          "The difference between request-scoped context (the subject's species) and global evaluation context (the trial's country), and when each is the right tool",
          "How hooks let you attach cross-cutting behaviour, audit logging today and OpenTelemetry tracing tomorrow, without modifying every flag evaluation call site",
        ],
      },
      {
        id: "expert",
        name: "Read the Chart",
        difficulty: "Expert",
        topics: ["OpenFeature", "OpenTelemetry", "Grafana", "Spring Boot"],
        learnings: [
          "How the OpenFeature OpenTelemetry hooks (TracesHook and MetricsHook) join flag evaluations to the rest of an application's telemetry without a separate ingestion path",
          "How to author your own Hook: a tiny class that copies merged-eval-context attributes onto the active OTel span, closing the loop between why a flag resolved the way it did and what the operator sees in Tempo",
          "How fractional rollout in flagd buckets users by targetingKey (same key, same bucket, every request) and how to read that bucketing off a dashboard",
          "How a flag flip is a faster operational lever than a redeploy when a rollout is misbehaving: the difference between a one-line config change and a twenty-minute deployment",
        ],
      },
    ],
  },
  {
    id: "the-ai-observatory",
    title: "The AI Observatory",
    month: "FEB 2026",
    story: "Investigate a mysterious bandwidth anomaly at a remote research station by instrumenting its AI system with OpenTelemetry, OpenLLMetry, and Jaeger.",
    tags: ["OpenTelemetry", "OpenLLMetry", "Jaeger", "Prometheus", "Python"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "DevRel at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    levels: [
      {
        id: "beginner",
        name: "Calibrating the Lens",
        difficulty: "Beginner",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger"],
        learnings: [
          "Instrument Python AI apps with OpenLLMetry",
          "Analyze traces in Jaeger",
        ],
      },
      {
        id: "intermediate",
        name: "The Distracted Pilot",
        difficulty: "Intermediate",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger", "Prometheus"],
        learnings: [
          "Instrument RAG pipelines with OpenLLMetry",
          "Create custom OpenTelemetry metrics in Python",
          "Write PromQL queries &#x26; recording rules in Prometheus",
        ],
      },
      {
        id: "expert",
        name: "The Noise Filter",
        difficulty: "Expert",
        topics: ["OpenTelemetry", "OpenLLMetry", "Jaeger"],
        learnings: [
          "OpenTelemetry GenAI semantic conventions",
          "Tail sampling in the OTel Collector",
        ],
      },
    ],
  },
  {
    id: "building-cloudhaven",
    title: "Building CloudHaven",
    month: "JAN 2026",
    story: "Join the Infrastructure Guild and modernize CloudHaven's infrastructure from manual provisioning to a self-service platform using Infrastructure as Code. A hands-on journey through infrastructure as code with OpenTofu and GitHub Actions.",
    tags: ["OpenTofu", "Terraform", "GitHub Actions", "Trivy", "TDD"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "DevRel at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    levels: [
      {
        id: "beginner",
        name: "The Foundation Stones",
        difficulty: "Beginner",
        topics: ["OpenTofu"],
        learnings: [
          "Infrastructure as Code with OpenTofu",
          "Remote state management with GCS backend",
          "Dynamic resource provisioning with for_each",
          "Conditional resources with the enabled meta-argument, new in OpenTofu",
        ],
      },
      {
        id: "intermediate",
        name: "The Modular Metropolis",
        difficulty: "Intermediate",
        topics: ["OpenTofu", "TDD"],
        learnings: [
          "OpenTofu module testing with tofu test",
          "Test-Driven Development (TDD) workflow",
          "Input validation with custom rules",
          "Refactoring infrastructure safely with moved blocks",
        ],
      },
      {
        id: "expert",
        name: "The Guardian Protocols",
        difficulty: "Expert",
        topics: ["OpenTofu", "GitHub Actions", "Trivy"],
        learnings: [
          "GitHub Actions for drift detection and plan/apply",
          "Integration tests with service containers",
          "Security scanning with Trivy",
        ],
      },
    ],
  },
  {
    id: "echoes-lost-in-orbit",
    title: "Echoes Lost in Orbit",
    month: "DEC 2025",
    story: "Restore interstellar communications by fixing broken GitOps setups, progressive delivery systems, and observability pipelines across three galactic missions.",
    tags: ["Argo CD", "Argo Rollouts", "OpenTelemetry", "Jaeger", "PromQL"],
    contributor: {
      name: "Katharina Sick",
      url: "https://ksick.dev/",
      aboutHtml: "DevRel at Dynatrace and co-organizer of Cloud Native Linz. Passionate about building user-friendly Cloud Native and Kubernetes solutions, with a background in mobile and backend development. Found in tech and sports communities, inline skating rinks, and quiz nights across Europe.",
    },
    levels: [
      {
        id: "beginner",
        name: "Broken Echoes",
        difficulty: "Beginner",
        topics: ["Argo CD"],
        learnings: [
          "Debug GitOps flows with Argo CD",
          "ApplicationSet templating &#x26; pitfalls",
          "Environment isolation &#x26; namespaces",
          "Sync policies: automated, prune &#x26; self-heal",
        ],
      },
      {
        id: "intermediate",
        name: "The Silent Canary",
        difficulty: "Intermediate",
        topics: ["Argo Rollouts", "PromQL"],
        learnings: [
          "Progressive delivery with Argo Rollouts",
          "Canary deployments &#x26; automated analysis",
          "Write PromQL queries for health validation",
          "Kube-state-metrics for deployment decisions",
        ],
      },
      {
        id: "expert",
        name: "Hyperspace Operations & Transport",
        difficulty: "Expert",
        topics: ["Argo Rollouts", "OpenTelemetry", "Jaeger", "PromQL"],
        learnings: [
          "Configure OpenTelemetry Collector pipelines",
          "Spanmetrics connector (traces to metrics)",
          "Detect idle canaries with traffic validation",
          "Distributed tracing with Jaeger",
        ],
      },
    ],
  },
];

/** All unique technology tags across all adventures, for card and filter views. */
export const SUMMARY_TAGS: string[] = Array.from(
  new Set(ADVENTURE_SUMMARIES.flatMap((a) => a.tags))
).sort();

/** Returns level summaries matching a tag, for filtered card views on the home page. */
export const getLevelSummariesByTag = (tag: string): RelatedLevelSummary[] =>
  ADVENTURE_SUMMARIES
    .filter((a) => a.tags.includes(tag))
    .flatMap((a) =>
      a.levels.map((level) => ({
        level,
        adventureId: a.id,
        adventureTitle: a.title,
        ...(a.isLive ? { isLive: true } : {}),
      }))
    );

/**
 * Community members who contributed an adventure, grouped by person.
 * Derived from ADVENTURE_SUMMARIES — import from here instead of "@/data/adventures"
 * on pages that do not otherwise need the full adventure dataset (About, Adventures, Challenges).
 */
export const ADVENTURE_CONTRIBUTORS: AdventureContributor[] = Object.values(
  ADVENTURE_SUMMARIES
    .filter((a): a is AdventureCardSummary & { contributor: NonNullable<AdventureCardSummary["contributor"]> } => a.contributor !== undefined)
    .reduce<Record<string, AdventureContributor>>((acc, a) => {
      const key = a.contributor.name;
      if (!acc[key]) {
        acc[key] = { name: a.contributor.name, url: a.contributor.url, aboutHtml: a.contributor.aboutHtml, adventures: [] };
      }
      acc[key].adventures.push({ id: a.id, title: a.title });
      return acc;
    }, {})
);
